### ISSUE TITLE
play.py: Joystick not responding since installing gym-mupen64plus

### ISSUE THREAD

**Issue by xaviervasques** [kevinhughes27/TensorKart#46] opened 2017-08-12 10:24 UTC
Hello, I think I am in the final step :)
I installed mupen64plus, my joystick, everything went smoothly. I run record.py, joystick inputs responding. I run play.py, I have the two screens opened but when the race starts, nothing, mario do not move. And I realized that my joystick in no more responding since I followed the installation of gym-mupen64plus.
If I start from scratch mupen64plus's install, it works. Then, when I install gym-mupen64plus, joystick doesn't work. The joystick is still recognized and get the right signals in record.py, when I test it through jstest, it is ok etc ... I think there is something modifying mupen64plus.
Can you please help me ? I am in the final step :))

**Comment by xaviervasques** [comment] 2017-08-12 10:57
By removing the configuration file (mupen64plus.cfg), if I run mupen64plus, my joystick works. 
So the problem is seems related to play.py

**Comment by xaviervasques** [comment] 2017-08-12 10:59
An here are the outputs:

xavi@ubuntu:~/Desktop/TensorKart$ python play.py 
Using TensorFlow backend.
[2017-08-12 03:58:17,883] Making new env: Mario-Kart-Royal-Raceway-v0
('ControllerHTTPServer started on port ', 8082)
initial_disp: :0
Starting emulator with comand: ['mupen64plus', '--resolution', '640x480', '--input', '/usr/local/lib/mupen64plus/mupen64plus-input-bot.so', '/home/xavi/Desktop/TensorKart/mupen64plus-src/gym-mupen64plus/gym_mupen64plus/ROMs/Mario_Kart_64.z64']
Calling wx.App() with DISPLAY: :0
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
UI-Console:             Includes support for MIPS r4300 Debugger.
Core: Couldn't open configuration file '/home/xavi/.config/mupen64plus/mupen64plus.cfg'.  Using defaults.
Core Warning: No version number in 'Core' config section. Setting defaults.
Core Warning: No version number in 'CoreEvents' config section. Setting defaults.
UI-Console Warning: No version number in 'UI-Console' config section. Setting defaults.
Core: Goodname: Mario Kart 64 (E) (V1.1) [!]
Core: Name: MARIOKART64         
Core: MD5: 2BB149A583FDEFEA96805F628FE42FD9
Core: CRC: 2577C7D4 D18FAAAE
Core: Imagetype: .z64 (native)
Core: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
Core: Version: 1446
Core: Manufacturer: Nintendo
Core: Country: Unknown (0x150)
UI-Console Status: Cheat codes disabled.
Video Warning: No version number in 'Rice-Video' config section. Setting defaults.
Video Warning: Old parameter config version detected : 0, updating to 1;
UI-Console: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.5.0
Audio Warning: No version number in 'Audio-SDL' config section. Setting defaults.
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
UI-Console: using Input plugin: 'Mupen64Plus Bot Input Plugin' v0.0.1
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Input: Mupen64Plus Bot Input Plugin version 0.0.1 initialized.
Video: SSE processing enabled.
Video: ROM (CRC d4c77725aeaa8fd1-50) not found in INI file
Video: Enabled hacks for game: 'MARIOKART64'
Video: Initializing OpenGL Device Context.
Core: Setting 32-bit video mode: 640x480
Video Warning: Failed to set GL_SWAP_CONTROL to 0. (it's 24)
Video Warning: Failed to set GL_BUFFER_SIZE to 32. (it's 24)
Video Warning: Failed to set GL_DEPTH_SIZE to 16. (it's 24)
Video: Using OpenGL: VMware, Inc. - Gallium 0.4 on SVGA3D; build: RELEASE;  LLVM; : 3.0 Mesa 17.0.7
Audio: Initializing SDL audio subsystem...
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7f9027d206e0
Changed DISPLAY to: :0
('Frame ', '10', ': ', '[0, 0, 1, 0, 0]')
('Frame ', '80', ': ', '[0, 0, 1, 0, 0]')
('Frame ', '120', ': ', '[0, 0, 1, 0, 0]')
('Frame ', '125', ': ', '[0, -80, 0, 0, 0]')
('Frame ', '130', ': ', '[0, 0, 1, 0, 0]')
('Frame ', '132', ': ', '[0, 0, 1, 0, 0]')
('Frame ', '134', ': ', '[0, 0, 1, 0, 0]')
('Player row: ', '0')
('Player col: ', '0')
('Frame ', '160', ': ', '[0, 0, 1, 0, 0]')
('Frame ', '162', ': ', '[0, 0, 1, 0, 0]')
('Map series: ', '2')
('Map choice: ', '2')
('Frame ', '196', ': ', '[80, 0, 0, 0, 0]')
('Frame ', '198', ': ', '[80, 0, 0, 0, 0]')
('Frame ', '202', ': ', '[0, 0, 1, 0, 0]')
('Frame ', '224', ': ', '[0, -80, 0, 0, 0]')
('Frame ', '226', ': ', '[0, -80, 0, 0, 0]')
('Frame ', '230', ': ', '[0, 0, 1, 0, 0]')
('Frame ', '232', ': ', '[0, 0, 1, 0, 0]')
Reset called!
env ready!
2017-08-12 03:58:41.885096: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-12 03:58:41.885133: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-12 03:58:41.885139: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-12 03:58:41.885142: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-12 03:58:41.885145: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
actor ready!
beginning episode loop
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]
AI: [0, 0, 0, 0, 0]

**Comment by kevinhughes27** [comment] 2017-08-12 15:47
To clarify you did complete the middle steps where you train the model on the data you recorded use record.py right?

**Comment by xaviervasques** [comment] 2017-08-12 18:55
Hello Kevin and thank you for your reply. You right. I did complete the model train on the data I recorded using record.py. I launched play.py.

**Comment by kevinhughes27** [comment] 2017-08-14 13:45
I am going to close this as a duplicate of https://github.com/bzier/gym-mupen64plus/issues/19 to keep the discussion easier to follow

**Closed by kevinhughes27** 2017-08-14 13:45 UTC
